<a href="https://colab.research.google.com/github/tarangga/Workspace-CICP-Twitter-Preprocessing/blob/main/Learn_Twitter_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Case Folding

In [1]:
doc1 = 'makan'
doc2 = 'Makan'

doc1 == doc2

False

In [2]:
new_doc2 = doc2.lower()
new_doc2

'makan'

In [3]:
doc1 == new_doc2

True

# Pembersihan URL, Mention, Hastag, reserve words, EMOJI, Smiley, Number 

In [4]:
! pip install tweet-preprocessor

In [5]:
text = 'kerja pemerintah memang nomor 1 #awesome 👍 https://xyz.co.id'

In [6]:
import preprocessor as p

In [7]:
p.set_options(p.OPT.URL)
p.clean(text)

'kerja pemerintah memang nomor 1 #awesome 👍'

In [8]:
p.set_options(p.OPT.MENTION)
p.clean(text)

'kerja pemerintah memang nomor 1 #awesome 👍 https://xyz.co.id'

In [9]:
p.set_options(p.OPT.HASHTAG, p.OPT.NUMBER)
p.clean(text)

'kerja pemerintah memang nomor 👍 https://xyz.co.id'

# Menghapus tanda baca

In [10]:
import re

re.sub(r'[^\w\s]', ' ', 'dia sedang, makan')

'dia sedang  makan'

# Speeling Correction

In [11]:
! git clone https://github.com/meisaputri21/Indonesian-Twitter-Emotion-Dataset/

Cloning into 'Indonesian-Twitter-Emotion-Dataset'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 69 (delta 0), reused 0 (delta 0), pack-reused 66
Unpacking objects: 100% (69/69), done.


In [12]:
f = open('/content/Indonesian-Twitter-Emotion-Dataset/kamus_singkatan.csv').read().strip()
print(f)

aamiin;amin 
adek;adik 
adlh;adalah 
aer;air 
aiskrim;es krim 
aj;saja 
aja;saja 
ajah;saja 
ajalah;saja 
aje;saja 
ajh;saja 
ajh;saja
ajj;saja
aku;saya
ak;saya 
akoh;saya
akutu;saya
aq;saya
alesan;alasan 
ama;sama 
amaca;ah masa
amuh;kamu
ancur;hancur 
ane;saya 
anget;hangat 
anjeng;anjing 
ank;anak 
apah;apa 
aph;apa
apo;apa 
apose;apa
apz;apa
aq;saya
artine;artinya 
asek;asik 
ati2;hati-hati 
atit;sakit 
atu;satu 
atw;atau 
ayang;sayang 
ayuk;ayo 
babang;abang
bae;baik 
bais;habis
bakalan;akan 
bales;balas 
bandingin;bandingkan 
banget;sekali 
bangett;sangat 
banyakin;perbanyak 
barengan;bersamaan 
baryaw;sabar ya
baso;bakso 
bay;selamat tinggal
bbrp;beberapa 
bc;baca 
bcs;bisa 
bct;bicara 
bdan;badan 
bdg;bandung 
bdn;badan 
becanda;bercanda 
bedua;berdua 
bego;bodoh 
bekel;bekal 
belom;belum 
belon;belum 
bener;benar 
bener2;benar-benar 
beneran;benar 
berantem;bertengkar 
berenti;berhenti 
besoq;besok
bete;sebal 
beud;banget
bg;bagi 
bgd;sangat 
bget;sangat 
bgini;begini 
bgitu;b

In [13]:
arr = f.split('\n')
arr

['aamiin;amin ',
 'adek;adik ',
 'adlh;adalah ',
 'aer;air ',
 'aiskrim;es krim ',
 'aj;saja ',
 'aja;saja ',
 'ajah;saja ',
 'ajalah;saja ',
 'aje;saja ',
 'ajh;saja ',
 'ajh;saja',
 'ajj;saja',
 'aku;saya',
 'ak;saya ',
 'akoh;saya',
 'akutu;saya',
 'aq;saya',
 'alesan;alasan ',
 'ama;sama ',
 'amaca;ah masa',
 'amuh;kamu',
 'ancur;hancur ',
 'ane;saya ',
 'anget;hangat ',
 'anjeng;anjing ',
 'ank;anak ',
 'apah;apa ',
 'aph;apa',
 'apo;apa ',
 'apose;apa',
 'apz;apa',
 'aq;saya',
 'artine;artinya ',
 'asek;asik ',
 'ati2;hati-hati ',
 'atit;sakit ',
 'atu;satu ',
 'atw;atau ',
 'ayang;sayang ',
 'ayuk;ayo ',
 'babang;abang',
 'bae;baik ',
 'bais;habis',
 'bakalan;akan ',
 'bales;balas ',
 'bandingin;bandingkan ',
 'banget;sekali ',
 'bangett;sangat ',
 'banyakin;perbanyak ',
 'barengan;bersamaan ',
 'baryaw;sabar ya',
 'baso;bakso ',
 'bay;selamat tinggal',
 'bbrp;beberapa ',
 'bc;baca ',
 'bcs;bisa ',
 'bct;bicara ',
 'bdan;badan ',
 'bdg;bandung ',
 'bdn;badan ',
 'becanda;bercand

In [14]:
arr = [a.split(';') for a in arr]
arr

[['aamiin', 'amin '],
 ['adek', 'adik '],
 ['adlh', 'adalah '],
 ['aer', 'air '],
 ['aiskrim', 'es krim '],
 ['aj', 'saja '],
 ['aja', 'saja '],
 ['ajah', 'saja '],
 ['ajalah', 'saja '],
 ['aje', 'saja '],
 ['ajh', 'saja '],
 ['ajh', 'saja'],
 ['ajj', 'saja'],
 ['aku', 'saya'],
 ['ak', 'saya '],
 ['akoh', 'saya'],
 ['akutu', 'saya'],
 ['aq', 'saya'],
 ['alesan', 'alasan '],
 ['ama', 'sama '],
 ['amaca', 'ah masa'],
 ['amuh', 'kamu'],
 ['ancur', 'hancur '],
 ['ane', 'saya '],
 ['anget', 'hangat '],
 ['anjeng', 'anjing '],
 ['ank', 'anak '],
 ['apah', 'apa '],
 ['aph', 'apa'],
 ['apo', 'apa '],
 ['apose', 'apa'],
 ['apz', 'apa'],
 ['aq', 'saya'],
 ['artine', 'artinya '],
 ['asek', 'asik '],
 ['ati2', 'hati-hati '],
 ['atit', 'sakit '],
 ['atu', 'satu '],
 ['atw', 'atau '],
 ['ayang', 'sayang '],
 ['ayuk', 'ayo '],
 ['babang', 'abang'],
 ['bae', 'baik '],
 ['bais', 'habis'],
 ['bakalan', 'akan '],
 ['bales', 'balas '],
 ['bandingin', 'bandingkan '],
 ['banget', 'sekali '],
 ['bangett', 's

In [15]:
cor = {kv[0].strip(): kv[1].strip() for kv in arr}
cor

{'aamiin': 'amin',
 'adek': 'adik',
 'adlh': 'adalah',
 'aer': 'air',
 'aiskrim': 'es krim',
 'aj': 'saja',
 'aja': 'saja',
 'ajah': 'saja',
 'ajalah': 'saja',
 'aje': 'saja',
 'ajh': 'saja',
 'ajj': 'saja',
 'aku': 'saya',
 'ak': 'saya',
 'akoh': 'saya',
 'akutu': 'saya',
 'aq': 'saya',
 'alesan': 'alasan',
 'ama': 'sama',
 'amaca': 'ah masa',
 'amuh': 'kamu',
 'ancur': 'hancur',
 'ane': 'saya',
 'anget': 'hangat',
 'anjeng': 'anjing',
 'ank': 'anak',
 'apah': 'apa',
 'aph': 'apa',
 'apo': 'apa',
 'apose': 'apa',
 'apz': 'apa',
 'artine': 'artinya',
 'asek': 'asik',
 'ati2': 'hati-hati',
 'atit': 'sakit',
 'atu': 'satu',
 'atw': 'atau',
 'ayang': 'sayang',
 'ayuk': 'ayo',
 'babang': 'abang',
 'bae': 'baik',
 'bais': 'habis',
 'bakalan': 'akan',
 'bales': 'balas',
 'bandingin': 'bandingkan',
 'banget': 'sekali',
 'bangett': 'sangat',
 'banyakin': 'perbanyak',
 'barengan': 'bersamaan',
 'baryaw': 'sabar ya',
 'baso': 'bakso',
 'bay': 'selamat tinggal',
 'bbrp': 'beberapa',
 'bc': 'baca'

In [16]:
def correction(sentence, cor=cor):
  new_sentence = ""
  for word in sentence.split():
    if word in cor.keys():
      new_sentence = new_sentence + cor[word] + ' '
    else:
      new_sentence = new_sentence + word + ' '
  return new_sentence

In [17]:
correction('sy sdh mkn nasi')

'saya sudah makan nasi '

# Stopword

## Sastrawi

In [18]:
! pip install Sastrawi

     |████████████████████████████████| 209 kB 9.2 MB/s 


In [19]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()

In [20]:
factory.get_stop_words()

['yang',
 'untuk',
 'pada',
 'ke',
 'para',
 'namun',
 'menurut',
 'antara',
 'dia',
 'dua',
 'ia',
 'seperti',
 'jika',
 'jika',
 'sehingga',
 'kembali',
 'dan',
 'tidak',
 'ini',
 'karena',
 'kepada',
 'oleh',
 'saat',
 'harus',
 'sementara',
 'setelah',
 'belum',
 'kami',
 'sekitar',
 'bagi',
 'serta',
 'di',
 'dari',
 'telah',
 'sebagai',
 'masih',
 'hal',
 'ketika',
 'adalah',
 'itu',
 'dalam',
 'bisa',
 'bahwa',
 'atau',
 'hanya',
 'kita',
 'dengan',
 'akan',
 'juga',
 'ada',
 'mereka',
 'sudah',
 'saya',
 'terhadap',
 'secara',
 'agar',
 'lain',
 'anda',
 'begitu',
 'mengapa',
 'kenapa',
 'yaitu',
 'yakni',
 'daripada',
 'itulah',
 'lagi',
 'maka',
 'tentang',
 'demi',
 'dimana',
 'kemana',
 'pula',
 'sambil',
 'sebelum',
 'sesudah',
 'supaya',
 'guna',
 'kah',
 'pun',
 'sampai',
 'sedangkan',
 'selagi',
 'sementara',
 'tetapi',
 'apakah',
 'kecuali',
 'sebab',
 'selain',
 'seolah',
 'seraya',
 'seterusnya',
 'tanpa',
 'agak',
 'boleh',
 'dapat',
 'dsb',
 'dst',
 'dll',
 'dahulu

In [21]:
stopword.remove('saya sekali-kali jalan-jalan ke amerika')

'sekali-kali jalan-jalan amerika'

## Spacy

In [22]:
from spacy.lang.id import STOP_WORDS

In [23]:
STOP_WORDS

{'ada',
 'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut'

In [24]:
def remove_stopword(text, stopwords):
  new_text = ''
  for word in text.split():
    if word not in stopwords:
      new_text = new_text + word + ' '
  return new_text

In [25]:
remove_stopword('saya sekali-kali jalan-jalan ke amerika', STOP_WORDS)

'jalan-jalan amerika '

## Stopword Buatan Sendiri

In [26]:
my_stopword = ['saya', 'sekali-kali']

In [27]:
remove_stopword('saya sekali-kali jalan-jalan ke amerika', my_stopword)

'jalan-jalan ke amerika '

# Gabungkan Semua

In [28]:
! git clone https://github.com/tarangga/Workspace-CICP-Twitter-Preprocessing

Cloning into 'Workspace-CICP-Twitter-Preprocessing'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.


In [30]:
import pandas as pd
df = pd.read_csv('/content/Workspace-CICP-Twitter-Preprocessing/data.csv', sep=';')
df

text
0  Selamat datang Yang Mulia Lee Hsien Loong, Per...
1  Ini Bupati Langkat rasanya bupati otak krimina...
2  Perbudakan modern adalah hal yg tidak bisa lag...
3  Ketika mnusia" lain bebas berteriak dan bersik...
4  Kalau PKS, pengurus tingkat RT aja bisa dikait...

In [39]:
df['clean'] = df['text'].apply(lambda x:str(x).lower())
df

text                                              clean
0  Selamat datang Yang Mulia Lee Hsien Loong, Per...  selamat datang yang mulia lee hsien loong, per...
1  Ini Bupati Langkat rasanya bupati otak krimina...  ini bupati langkat rasanya bupati otak krimina...
2  Perbudakan modern adalah hal yg tidak bisa lag...  perbudakan modern adalah hal yg tidak bisa lag...
3  Ketika mnusia" lain bebas berteriak dan bersik...  ketika mnusia" lain bebas berteriak dan bersik...
4  Kalau PKS, pengurus tingkat RT aja bisa dikait...  kalau pks, pengurus tingkat rt aja bisa dikait...

In [40]:
df['clean'] = df['clean'].apply(p.clean)
df

text                                              clean
0  Selamat datang Yang Mulia Lee Hsien Loong, Per...  selamat datang yang mulia lee hsien loong, per...
1  Ini Bupati Langkat rasanya bupati otak krimina...  ini bupati langkat rasanya bupati otak krimina...
2  Perbudakan modern adalah hal yg tidak bisa lag...  perbudakan modern adalah hal yg tidak bisa lag...
3  Ketika mnusia" lain bebas berteriak dan bersik...  ketika mnusia" lain bebas berteriak dan bersik...
4  Kalau PKS, pengurus tingkat RT aja bisa dikait...  kalau pks, pengurus tingkat rt aja bisa dikait...

In [41]:
df['clean'] = df['clean'].apply(lambda x:re.sub(r'[^\w\s]', '', str(x)))
df

text                                              clean
0  Selamat datang Yang Mulia Lee Hsien Loong, Per...  selamat datang yang mulia lee hsien loong perd...
1  Ini Bupati Langkat rasanya bupati otak krimina...  ini bupati langkat rasanya bupati otak krimina...
2  Perbudakan modern adalah hal yg tidak bisa lag...  perbudakan modern adalah hal yg tidak bisa lag...
3  Ketika mnusia" lain bebas berteriak dan bersik...  ketika mnusia lain bebas berteriak dan bersika...
4  Kalau PKS, pengurus tingkat RT aja bisa dikait...  kalau pks pengurus tingkat rt aja bisa dikaitk...

In [42]:
df['clean'] = df['clean'].apply(p.clean)
df

text                                              clean
0  Selamat datang Yang Mulia Lee Hsien Loong, Per...  selamat datang yang mulia lee hsien loong perd...
1  Ini Bupati Langkat rasanya bupati otak krimina...  ini bupati langkat rasanya bupati otak krimina...
2  Perbudakan modern adalah hal yg tidak bisa lag...  perbudakan modern adalah hal yg tidak bisa lag...
3  Ketika mnusia" lain bebas berteriak dan bersik...  ketika mnusia lain bebas berteriak dan bersika...
4  Kalau PKS, pengurus tingkat RT aja bisa dikait...  kalau pks pengurus tingkat rt aja bisa dikaitk...

In [43]:
df['clean'] = df['clean'].apply(lambda x: correction(str(x), cor=cor))
df

text                                              clean
0  Selamat datang Yang Mulia Lee Hsien Loong, Per...  selamat datang yang mulia lee hsien loong perd...
1  Ini Bupati Langkat rasanya bupati otak krimina...  ini bupati langkat rasanya bupati otak krimina...
2  Perbudakan modern adalah hal yg tidak bisa lag...  perbudakan modern adalah hal yang tidak bisa l...
3  Ketika mnusia" lain bebas berteriak dan bersik...  ketika mnusia lain bebas berteriak dan bersika...
4  Kalau PKS, pengurus tingkat RT aja bisa dikait...  kalau pks pengurus tingkat rt saja bisa dikait...

In [44]:
df['clean'] = df['clean'].apply(lambda x: remove_stopword(str(x), STOP_WORDS))
df

text                                              clean
0  Selamat datang Yang Mulia Lee Hsien Loong, Per...  selamat mulia lee hsien loong perdana menteri ...
1  Ini Bupati Langkat rasanya bupati otak krimina...  bupati langkat bupati otak kriminal berlapis l...
2  Perbudakan modern adalah hal yg tidak bisa lag...  perbudakan modern tolerirsaya khawatir satu2 n...
3  Ketika mnusia" lain bebas berteriak dan bersik...  mnusia bebas berteriak bersikapko orangin hidu...
4  Kalau PKS, pengurus tingkat RT aja bisa dikait...  pks pengurus tingkat rt dikaitkan partai beda ...

# Hugginface

In [52]:
! pip install transformers --quiet
! pip install sentencepiece --quiet
! pip install transformers[sentencepiece] --quiet

## Terjemahan

In [1]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-id-en")

model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-id-en")

Downloading:   0%|          | 0.00/782k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/777k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.20M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/278M [00:00<?, ?B/s]

In [14]:
text = ['hai saya lagi pengen ke luar negeri']

In [31]:
tokens = tokenizer(text, return_tensors='pt')
tokens

{'input_ids': tensor([[ 2189,    85,   151, 24034,    64,   547,  1061,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [47]:
pred_tokens = model.generate(**tokens)
pred_tokens

tensor([[54795,   614,     7,   156,    12,   116, 12361,     0]])

In [51]:
tokenizer.decode(pred_tokens[0], skip_special_tokens=True)

'Hi I want to go abroad'

# Klasifikasi teks

In [76]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")

model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")

Downloading:   0%|          | 0.00/252 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/758 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/418M [00:00<?, ?B/s]

In [106]:
text = ['this is was so expensive, i hate that']

In [107]:
tokens = tokenizer(text, return_tensors='pt')
tokens

{'input_ids': tensor([[ 101, 2023, 2003, 2001, 2061, 6450, 1010, 1045, 5223, 2008,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [108]:
pred = model(input_ids=tokens['input_ids'])
pred
# 0 -> positive, 1-> negative, 2-> netral

SequenceClassifierOutput([('logits',
                           tensor([[-1.7818,  2.1345,  0.3823]], grad_fn=<AddmmBackward0>))])

In [109]:
import numpy as np
np.argmax(pred[0].detach().numpy(), axis=1)

array([1])

In [101]:
pred[0]

tensor([[ 0.2555, -1.9677,  2.0776]], grad_fn=<AddmmBackward0>)